# Generated by Django 3.1.4 on 2021-02-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiolyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('audio', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
