# Generated by Django 3.1.7 on 2021-04-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_auto_20210411_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
