# Generated by Django 3.1.7 on 2021-04-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_auto_20210411_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='title',
        ),
        migrations.AlterField(
            model_name='poster',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
